server:
  basePrefixUrl: /api/v1/users
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${spring.liquibase.parameters.defaultSchemaName}
    url: jdbc:postgresql://localhost:5432/user_db?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default-schema: ${spring.liquibase.parameters.defaultSchemaName}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        connection:
          CharSet: utf8
          characterEncoding: utf8
          useUnicode: utf8
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/changelog-master.xml
    parameters:
      defaultSchemaName: users
      driver-class-name: ${spring.datasource.driver-class-name}
      change-log: db/changelog-master.xml
preliquibase:
  dbPlatformCode: postgresql
  sqlScriptReferences: classpath:db/schema-init.sql