server:
  basePrefixUrl: /api/v1/users
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${spring.jpa.properties.hibernate.default_schema}
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default-schema: ${spring.liquibase.default-schema}
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    default-schema: users
    change-log: db/changelog-master.xml
preliquibase:
  dbPlatformCode: postgresql
  sqlScriptReferences: classpath:db/schema-init.sql